#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings

# yabai -m config                                 \
#     mouse_follows_focus          off            \
#     focus_follows_mouse          off            \
#     window_origin_display        default        \
#     window_placement             second_child   \
#     window_zoom_persist          on             \
#     window_topmost               off            \
#     window_shadow                on             \
#     window_animation_duration    0.0            \
#     window_animation_frame_rate  120            \
#     window_opacity_duration      0.0            \
#     active_window_opacity        1.0            \
#     normal_window_opacity        0.90           \
#     window_opacity               off            \
#     insert_feedback_color        0xffd75f5f     \
#     active_window_border_color   0xff775759     \
#     normal_window_border_color   0xff555555     \
#     window_border_width          4              \
#     window_border_radius         12             \
#     window_border_blur           off            \
#     window_border_hidpi          on             \
#     window_border                off            \
#     split_ratio                  0.50           \
#     split_type                   auto           \
#     auto_balance                 off            \
#     top_padding                  12             \
#     bottom_padding               12             \
#     left_padding                 12             \
#     right_padding                12             \
#     window_gap                   06             \
#     layout                       bsp            \
#     mouse_modifier               fn             \
#     mouse_action1                move           \
#     mouse_action2                resize         \
#     mouse_drop_action            swap

# echo "yabai configuration loaded.."

###############################
###### Ray Configuration ######
###############################
# 官方文档：https://github.com/koekeishiya/yabai/wiki/Configuration#configuration-file

sudo /opt/homebrew/bin/yabai --load-sa
/opt/homebrew/bin/yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"

# global settings
/opt/homebrew/bin/yabai -m config mouse_follows_focus          off
/opt/homebrew/bin/yabai -m config focus_follows_mouse          off
/opt/homebrew/bin/yabai -m config window_origin_display        default
/opt/homebrew/bin/yabai -m config window_placement             second_child
/opt/homebrew/bin/yabai -m config window_topmost               off
/opt/homebrew/bin/yabai -m config window_shadow                on

# 窗口透明度设置
/opt/homebrew/bin/yabai -m config window_opacity               off # 只有on下面配置才能生效
/opt/homebrew/bin/yabai -m config window_opacity_duration      0.0
# 激活窗口透明度
/opt/homebrew/bin/yabai -m config active_window_opacity        1.0
# 普通窗口透明度
/opt/homebrew/bin/yabai -m config normal_window_opacity        0.9

/opt/homebrew/bin/yabai -m config window_border                off
/opt/homebrew/bin/yabai -m config window_border_width          6
/opt/homebrew/bin/yabai -m config active_window_border_color   0xff775759
/opt/homebrew/bin/yabai -m config normal_window_border_color   0xff555555
/opt/homebrew/bin/yabai -m config insert_feedback_color        0xffd75f5f
/opt/homebrew/bin/yabai -m config split_ratio                  0.50
/opt/homebrew/bin/yabai -m config auto_balance                 off
/opt/homebrew/bin/yabai -m config mouse_modifier               fn
/opt/homebrew/bin/yabai -m config mouse_action1                move
/opt/homebrew/bin/yabai -m config mouse_action2                resize
/opt/homebrew/bin/yabai -m config mouse_drop_action            swap

# general space settings
/opt/homebrew/bin/yabai -m config layout                       bsp
# 上下左右间隙
/opt/homebrew/bin/yabai -m config top_padding                  00
/opt/homebrew/bin/yabai -m config bottom_padding               00
/opt/homebrew/bin/yabai -m config left_padding                 00
/opt/homebrew/bin/yabai -m config right_padding                00
# 窗口之间间隙
/opt/homebrew/bin/yabai -m config window_gap                   10
# yabai -m config window_animation_duration    0.00

/opt/homebrew/bin/yabai -m rule --add app="^iStat*" sticky=on layer=above manage=off border=off
/opt/homebrew/bin/yabai -m rule --add app="^System Preferences*" manage=off

echo "yabai configuration loaded.."
